apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sgu1t4od6-java-springboot
  janus-idp.io/tekton: sgu1t4od6-java-springboot
  backstage.io/kubernetes-id: sgu1t4od6-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sgu1t4od6-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
